driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
    name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[diamond::cpu]
      - recipe[diamond::memory]
      - recipe[diamond::diskspace]
