driver:
  name: vagrant

verifier:
  name: inspec
  format: doc

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.11
    # Set due to https://github.com/test-kitchen/kitchen-vagrant/issues/293
    driver:
      kitchen_cache_directory: .kitchen/cache/debian
    run_list:
      - recipe[apt::default]
  - name: debian-8.7
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[diamond::cpu]
      - recipe[diamond::memory]
      - recipe[diamond::diskspace]
