driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[diamond::cpu]
      - recipe[diamond::memory]
      - recipe[diamond::diskspace]
