Encoding:
  Enabled: false

LineLength:
  Enabled: false

NumericLiterals:
  MinDigits: 7

MethodLength:
  Max: 20

CyclomaticComplexity:
  Max: 10

SpaceBeforeFirstArg:
  Enabled: false

Next:
  Enabled: false

FileName:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/*'
